name: Test action

on:
  # Trigger whenever a release is created
  release:
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Use this action
        uses: ./
