name: Test action

on:
  # Trigger whenever a release is created
  release:
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use this action
        uses: ./
        with:
          input-repo: ${{ env.GITHUB_REPOSITORY }}
          output-repo: ${{ env.GITHUB_REPOSITORY }}
